version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: KiriBlog-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: KiriBlog_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: KiriBlog-azurite
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    volumes:
      - azurite_data:/data

volumes:
  postgres_data:
  azurite_data:
